source "https://rubygems.org"

#scraper deps
gem 'nokogiri'
gem 'mechanize'
gem 'pry', :group => 'development'

gem 'excon'
gem 'turbot-api', :path => '/Users/xavierriley/openc/turbot-api'
gem 'turbot', :path => '/Users/xavierriley/openc/turbot-client'
